## 1. Imports & Environment Setup

In [18]:
# Initial Imports
from pathlib import Path
import datetime
import json
import pandas as pd
import sys, os
from dotenv import load_dotenv
from mozzarellm.utils.io import load_table
from mozzarellm.utils.screen_context_utils import load_screen_context_json
from mozzarellm.pipeline.bundle_builder import (
    build_evidence_bundles,
    get_or_append_stable_accession,
)
from mozzarellm.pipeline.literature_mcp import get_available_mcp_servers
from mozzarellm.clients.llm_api_clients import create_client
from mozzarellm.utils.prompt_factory import (
    make_cluster_analysis_system_prompt,
    make_single_cluster_analysis_user_prompt,
)
from mozzarellm.utils.cluster_utils import build_cluster_id_to_bundle_path
from mozzarellm.utils.trace import save_trace

print(sys.path)

['C:\\Users\\alexa\\OneDrive - Massachusetts Institute of Technology\\Cheesman Lab\\WORKSPACE\\mozzarellm', 'C:\\Users\\alexa\\AppData\\Local\\Python\\pythoncore-3.12-64\\python312.zip', 'C:\\Users\\alexa\\AppData\\Local\\Python\\pythoncore-3.12-64\\DLLs', 'C:\\Users\\alexa\\AppData\\Local\\Python\\pythoncore-3.12-64\\Lib', 'C:\\Users\\alexa\\AppData\\Local\\Python\\pythoncore-3.12-64', 'c:\\Users\\alexa\\OneDrive - Massachusetts Institute of Technology\\Cheesman Lab\\WORKSPACE\\mozzarellm\\.mozzvenv', '', 'c:\\Users\\alexa\\OneDrive - Massachusetts Institute of Technology\\Cheesman Lab\\WORKSPACE\\mozzarellm\\.mozzvenv\\Lib\\site-packages', '__editable__.mozzarellm-0.2.0.finder.__path_hook__']

In [19]:
def _find_repo_root(start_dir: Path) -> Path:
    start_dir = start_dir.resolve()
    for p in [start_dir] + list(start_dir.parents):
        if (p / "pyproject.toml").exists():
            return p
    raise RuntimeError(f"Could not find pyproject.toml starting from {start_dir}")


# Use repo root for sys.path and for locating .env, regardless of notebook working directory (less brittle).
repo_root = _find_repo_root(Path(os.getcwd()))
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

# Load secrets/config from .env at the repo root (if present)
print("Does .env exist in repo root?", (repo_root / ".env").exists())
load_dotenv(dotenv_path=repo_root / ".env")
print("Repo root:", repo_root)
print("Current working directory:", os.getcwd())

Does .env exist in repo root? True
Repo root: C:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm
Current working directory: c:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm\interface

## 2. Screen Context Configuration

Complete the `screen_context.json` file with the relevant information for your screen. Feel free to adjust the template as needed beyond the required fields. The top level must be a dictionary, and all fields must be strings. Keep the file in the same directory as the notebook. This cell will check for the file and raise an error if it is not found or not well formatted.

In [20]:
# set screen name
SCREEN_NAME = f"mcpmodbranch_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}"
SCREEN_CONTEXT_PATH = Path("screen_context.json")  # or change to your custom filename.
screen_ctx = load_screen_context_json(SCREEN_CONTEXT_PATH)
# should throw error if file doesn't exist or if you forgot to remove the TODO!

print("Loaded screen_context.json:", isinstance(screen_ctx, dict))
keys = list(screen_ctx.keys())
print(f"Top-level keys ({len(keys)}): {keys}")

Loaded screen_context.json: True
Top-level keys (10): ['assay_type', 'target_phenotype', 'organism', 'cell_line_or_system', 'perturbation', 'readout', 'clustering', 'controls', 'provenance', 'notes']

## 3. Load & Standardize Cluster Table 
### **3.1** Initial Load
Set parameters and check that the original cluster table loads.

In [21]:
#### 3.1.1 Point this to your cluster/gene table (CSV/TSV/TXT/XLSX) ####
default_cluster_table = (
    repo_root / "examples" / "ops" / "funk_2022.csv"
)  # NOTE: using funk_2022.csv for development
CLUSTER_TABLE_PATH = Path(default_cluster_table)

#### 3.1.2 Optional: ####
sep = None
# Useful for .txt files. If the table loads as one big column (or in an otherwise wonky fashion), the delimiter is likely mismatched.
# By default pandas ASSUMES the delimiter (value separator) based on file extension
# (typically .csv → ',', .tsv → '\t'). Common overrides are ',', '|', '\t', or ';'.

sheet_name = None
# For Excel only (e.g. 0 or 'Sheet1'); ignored for CSV/TSV
#########################

CLUSTER_DF = load_table(CLUSTER_TABLE_PATH, sep=sep, sheet_name=sheet_name)
print("Loaded:", str(CLUSTER_TABLE_PATH))
print("Shape:", CLUSTER_DF.shape)
print("Columns:\n", list(CLUSTER_DF.columns))
display(CLUSTER_DF.head())

Loaded: C:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm\examples\ops\funk_2022.csv
Shape: (164, 5)
Columns:
 ['gene_symbol', 'cluster', 'up_features', 'down_features', 'phenotypic_strength']

,gene_symbol,cluster,up_features,down_features,phenotypic_strength
0,AATF,21,"interphase_cell_correlation_dapi_tubulin,inter...","interphase_nucleus_area,interphase_cell_area,i...",669/5299
1,ABT1,21,"interphase_nucleus_gh2ax_mean,interphase_nucle...","interphase_nucleus_area,interphase_cell_area,i...",560/5299
2,BMS1,21,"interphase_nucleus_dapi_mean,interphase_cell_c...","interphase_nucleus_area,interphase_cell_area,i...",446/5299
3,BYSL,21,"interphase_nucleus_dapi_mean,interphase_cell_c...","interphase_nucleus_area,interphase_cell_area,i...",524/5299
4,C1orf131,21,"interphase_nucleus_dapi_mean,interphase_cell_c...","interphase_nucleus_area,interphase_cell_area,i...",343/5299

### **3.2** Gene to stable accession ID mapping

If you do not have stable accession IDs in your cluster table, we will make a best effort attempt to assign them based on your provided gene symbols (NOTE: the `get_accession_from_gene_symbol` method is available for review in `clients/uniprot_api_client.py`).

If you have a gene to stable accession IDs maping available separately from your cluster table, you can provide this table, and we will append the accession IDs to your cluster table. 

A csv copy of the assigned or appended gene to stable accession mapping will be provided for review in the `interface/output/` directory.

In [22]:
# set cluster id column name or keep default
CLUSTER_ID_COLUMN = "cluster"
# set gene column name or keep default
GENE_COLUMN = "gene_symbol"

# If you have a stable accession column already in your cluster table, set it here.
# If no stable accession column, leave as None and we'll handle it for you.
STABLE_ACCESSION_COLUMN = None  # or the name of your stable accession column

# List of per-gene feature columns that would be useful to determine overlaps for within a cluster.
FEATURE_COLUMNS = [
    "up_features",
    "down_features",
]

# Set organism id or keep default
ORGANISM_ID = 9606  # human

if STABLE_ACCESSION_COLUMN is None:
    ACC_CLUSTER_DF = get_or_append_stable_accession(
        screen_name=SCREEN_NAME,
        cluster_df=CLUSTER_DF,
        gene_column=GENE_COLUMN,
        organism_id=ORGANISM_ID,
        # SET WARNING SETTING: default is to ignore warnings for unreviewed entries
        warn_on_fallback=False,
        # IF ADDING A SEPERATE TABLE, SET THESE:
        accession_table=None,  # or Path("path/to/accession_table.csv")
        accession_col=None,  # or the name of your stable accession column in the seperate table
        accession_table_gene_col=None,  # or the name of your gene column in the seperate table
        accession_table_sheetname=None,  # or the sheet name for the seperate table if it's an excel file
        accession_table_sep=None,  # or the delimiter for the seperate table (use if you encounter encoding issues)
    )

# NOTE: Currently, running this cell will overwrite the last .csv output.
# TODO: (later) add option to prevent overwriting with a timestamp in filename. [just a hassle during iteration]
ACC_CLUSTER_DF

Assigned accession numbers to cluster df. Saved to:  output\mcpmodbranch_20260511_043334_analysis\intermediates\assigned_accession_cluster_df.csv

,gene_symbol,cluster,up_features,down_features,phenotypic_strength,accession
0,AATF,21,"interphase_cell_correlation_dapi_tubulin,inter...","interphase_nucleus_area,interphase_cell_area,i...",669/5299,Q9NY61
1,ABT1,21,"interphase_nucleus_gh2ax_mean,interphase_nucle...","interphase_nucleus_area,interphase_cell_area,i...",560/5299,Q9ULW3
2,BMS1,21,"interphase_nucleus_dapi_mean,interphase_cell_c...","interphase_nucleus_area,interphase_cell_area,i...",446/5299,Q14692
3,BYSL,21,"interphase_nucleus_dapi_mean,interphase_cell_c...","interphase_nucleus_area,interphase_cell_area,i...",524/5299,Q13895
4,C1orf131,21,"interphase_nucleus_dapi_mean,interphase_cell_c...","interphase_nucleus_area,interphase_cell_area,i...",343/5299,Q8NDD1
...,...,...,...,...,...,...
159,nontargeting_5_2,99,NaN,NaN,5203/5299,NON_TARGETING_CONTROL
160,nontargeting_61_0,99,NaN,NaN,5038/5299,NON_TARGETING_CONTROL
161,nontargeting_6_1,99,NaN,interphase_cell_phalloidin_mean,5237/5299,NON_TARGETING_CONTROL
162,nontargeting_8_2,99,NaN,NaN,5271/5299,NON_TARGETING_CONTROL
163,nontargeting_9_0,99,NaN,NaN,5197/5299,NON_TARGETING_CONTROL

## 4. Create Per-Cluster Evidence Bundles

Bundles will be saved to the `interface/output` directory. Additionally, each chunk has retrieved annotations and evidence logged in a corresponding csv file within the same directory. These can be accessed via File Explorer and viewed in Excel or Google Sheets.

In [23]:
build_evidence_bundles(
    screen_name=SCREEN_NAME,
    acc_cluster_df=ACC_CLUSTER_DF,  # cluster table must have accession numbers
    gene_column=GENE_COLUMN,
    cluster_id_column=CLUSTER_ID_COLUMN,
    stable_accession_col=STABLE_ACCESSION_COLUMN or "accession",
    feature_columns=FEATURE_COLUMNS,
    use_retrieval=False,  # false for now; true for future use
    knowledge_dir=None,
    top_k=5,
)

Using gene column: gene_symbol
Processing 7 clusters
Processing cluster 21
Saved bundle to output\mcpmodbranch_20260511_043334_analysis\mcpmodbranch_20260511_043334_evidence_bundles\mcpmodbranch_20260511_043334__cluster_21__bundle.json
Processing cluster 37
Saved bundle to output\mcpmodbranch_20260511_043334_analysis\mcpmodbranch_20260511_043334_evidence_bundles\mcpmodbranch_20260511_043334__cluster_37__bundle.json
Processing cluster 121
Saved bundle to output\mcpmodbranch_20260511_043334_analysis\mcpmodbranch_20260511_043334_evidence_bundles\mcpmodbranch_20260511_043334__cluster_121__bundle.json
Processing cluster 149
Saved bundle to output\mcpmodbranch_20260511_043334_analysis\mcpmodbranch_20260511_043334_evidence_bundles\mcpmodbranch_20260511_043334__cluster_149__bundle.json
Processing cluster 167
Saved bundle to output\mcpmodbranch_20260511_043334_analysis\mcpmodbranch_20260511_043334_evidence_bundles\mcpmodbranch_20260511_043334__cluster_167__bundle.json
Processing cluster 197
Saved bundle to output\mcpmodbranch_20260511_043334_analysis\mcpmodbranch_20260511_043334_evidence_bundles\mcpmodbranch_20260511_043334__cluster_197__bundle.json
Processing cluster 99
Saved bundle to output\mcpmodbranch_20260511_043334_analysis\mcpmodbranch_20260511_043334_evidence_bundles\mcpmodbranch_20260511_043334__cluster_99__bundle.json

C:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm\mozzarellm\clients\uniprot_api_client.py:253: UserWarning: 16 accession(s) found but lack FUNCTION annotations: ['Q9BVI4', 'Q5JTH9', 'Q9BSC4', 'Q3SX64', 'Q66K80']...
  warnings.warn(
C:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm\mozzarellm\clients\uniprot_api_client.py:253: UserWarning: 6 accession(s) found but lack FUNCTION annotations: ['Q96PV6', 'Q96BW1', 'P28290', 'Q8WU58', 'A5PLN9']...
  warnings.warn(
C:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm\mozzarellm\clients\uniprot_api_client.py:253: UserWarning: 7 accession(s) found but lack FUNCTION annotations: ['Q9NT22', 'Q0D2H9', 'Q96KN3', 'Q6P1L5', 'Q96PV6']...
  warnings.warn(
C:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm\mozzarellm\clients\uniprot_api_client.py:253: UserWarning: 11 accession(s) found but lack FUNCTION annotations: ['Q9BQC6', 'Q7Z7F7', 'Q8N7B6', 'Q8IUW3', 'Q16204']...
  warnings.warn(
C:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm\mozzarellm\clients\uniprot_api_client.py:253: UserWarning: 9 accession(s) found but lack FUNCTION annotations: ['Q14D33', 'Q66K80', 'Q8TBB0', 'Q6RVD6', 'P79522']...
  warnings.warn(
C:\Users\alexa\OneDrive - Massachusetts Institute of Technology\Cheesman Lab\WORKSPACE\mozzarellm\mozzarellm\clients\uniprot_api_client.py:253: UserWarning: 1 accession(s) found but lack FUNCTION annotations: ['Q9BYZ2']
  warnings.warn(

In [24]:
# build cluster ID to evidence bundle path mapping
BUNDLES_DIR = Path(
    f"output/{SCREEN_NAME}_analysis/{SCREEN_NAME}_evidence_bundles"
)  # check that this aligns with the output dir above
CLUSTER_ID_TO_BUNDLE_PATH_MAP = build_cluster_id_to_bundle_path(
    BUNDLES_DIR, screen_name=SCREEN_NAME
)
CLUSTER_ID_TO_BUNDLE_PATH_MAP

{'121': WindowsPath('output/mcpmodbranch_20260511_043334_analysis/mcpmodbranch_20260511_043334_evidence_bundles/mcpmodbranch_20260511_043334__cluster_121__bundle.json'),
 '149': WindowsPath('output/mcpmodbranch_20260511_043334_analysis/mcpmodbranch_20260511_043334_evidence_bundles/mcpmodbranch_20260511_043334__cluster_149__bundle.json'),
 '167': WindowsPath('output/mcpmodbranch_20260511_043334_analysis/mcpmodbranch_20260511_043334_evidence_bundles/mcpmodbranch_20260511_043334__cluster_167__bundle.json'),
 '197': WindowsPath('output/mcpmodbranch_20260511_043334_analysis/mcpmodbranch_20260511_043334_evidence_bundles/mcpmodbranch_20260511_043334__cluster_197__bundle.json'),
 '21': WindowsPath('output/mcpmodbranch_20260511_043334_analysis/mcpmodbranch_20260511_043334_evidence_bundles/mcpmodbranch_20260511_043334__cluster_21__bundle.json'),
 '37': WindowsPath('output/mcpmodbranch_20260511_043334_analysis/mcpmodbranch_20260511_043334_evidence_bundles/mcpmodbranch_20260511_043334__cluster_37__bundle.json'),
 '99': WindowsPath('output/mcpmodbranch_20260511_043334_analysis/mcpmodbranch_20260511_043334_evidence_bundles/mcpmodbranch_20260511_043334__cluster_99__bundle.json')}

## 5. LLM Analysis (Initial Hypothesis Formation)

All execution paths route through a single `client.analyze(...)` call. Per-cluster traces (response text, tool calls, tokens, cost, schema warnings) are written to `output/<screen>_analysis/traces/cluster_<id>.json`.

### 5.1 Run Configuration

Three knobs:

| Knob | Values | Notes |
|---|---|---|
| `MODE` | `standard` / `cot` / `stepwise` | `standard` = one call w/ rules-based prompt (historical default). `cot` = one call w/ numbered CoT steps. `stepwise` = N multi-turn calls (partial trace on failure). |
| `USE_MCP` | `False` / `True` | `True` attaches PubMed tools. Adds a literature-validation step. |
| `QUERY_TYPE` | `single` / `iterative` / `batch` | Execution shape. `batch` is incompatible with `USE_MCP=True` and `MODE='stepwise'` (Anthropic batch API doesn't support beta MCP, and stepwise needs multi-turn). |

MCP preflight runs here so you bail before paying for prompt construction.

In [25]:
MODEL = "claude-sonnet-4-6"
MODE = "cot"  # "standard" | "cot" | "stepwise"
USE_MCP = True  # attach PubMed MCP tools
QUERY_TYPE = "single"  # "single" | "iterative" | "batch"

# Used only when QUERY_TYPE == "single" (smoke-test path).
PREVIEW_CLUSTER_ID = "121"
TRUNCATE_PREVIEWS = True  # If false, pretty prints full prompts to console

# --- validation ---
if QUERY_TYPE == "batch" and (USE_MCP or MODE == "stepwise"):
    raise ValueError(
        "QUERY_TYPE='batch' is incompatible with USE_MCP=True or MODE='stepwise'. "
        "Anthropic's batch API does not support beta MCP, and stepwise needs multi-turn."
    )

# --- MCP preflight (only when actually using MCP) ---
if USE_MCP:
    print("MCP preflight:")
    available = get_available_mcp_servers()
    if "pubmed" not in available:
        raise RuntimeError("PubMed MCP server unavailable — run again later or set USE_MCP=False")
    print("  ✓ PubMed reachable")

RUN_DIR = Path(f"output/{SCREEN_NAME}_analysis")
RUN_DIR.mkdir(parents=True, exist_ok=True)
print(f"\nMODEL={MODEL}  MODE={MODE}  USE_MCP={USE_MCP}  QUERY_TYPE={QUERY_TYPE}")
print(f"Output dir: {RUN_DIR}")

MCP preflight:
  ✓ anthropic status page: operational (HTTP 200)
  ✓ pubmed MCP: up (HTTP 405)
  ✓ PubMed reachable

MODEL=claude-sonnet-4-6  MODE=cot  USE_MCP=True  QUERY_TYPE=single
Output dir: output\mcpmodbranch_20260511_043334_analysis

### 5.2 Prompt Construction

`make_cluster_analysis_system_prompt(mode=MODE, mcp=USE_MCP, ...)` builds the prompt per mode. `standard` = flat rules-based prompt (TASK + RULES + OUTPUT_FORMAT, with the lit step appended when `mcp=True`); `cot` = numbered CoT chain (one API call); `stepwise` = system holds task + screen context only (runner walks remaining steps as user turns).

In [26]:
SYSTEM_PROMPT = make_cluster_analysis_system_prompt(
    screen_name=SCREEN_NAME,
    screen_context_path=SCREEN_CONTEXT_PATH,
    mode=MODE,
    mcp=USE_MCP,
    template_path=None,
    template_string=None,
    output_dir=None,
)
if TRUNCATE_PREVIEWS:
    print(SYSTEM_PROMPT[:1500] + ("\n...\n[truncated]" if len(SYSTEM_PROMPT) > 1500 else ""))
else:
    print(SYSTEM_PROMPT)

STEP 1 -
MISSION: Functional genomics experiments cluster genes by phenotypic similarity. Your goal is to:
1. Identify the dominant biological pathway that explains why these genes cluster together
2. Categorize ALL genes relative to this pathway (ESTABLISHED / UNCHARACTERIZED / NOVEL_ROLE)
3. Prioritize understudied genes (UNCHARACTERIZED and NOVEL_ROLE) for follow-up experiments

The pathway is not the end goal - it's the lens for discovering which genes merit investigation.


STEP 2 - Review the provided screen context:
{"assay_type": "Optical Pooled Screen (OPS)", "target_phenotype": "Morphological cell phenotype — cell and nuclear shape, texture, and intensity features across multiple imaging channels", "organism": "Homo sapiens", "cell_line_or_system": "A549 (human lung adenocarcinoma epithelial cells)", "perturbation": {"type": "CRISPR-Cas9 knockout", "library_or_reagent": "Genome-wide sgRNA library (Funk et al. 2022)"}, "readout": {"measurement": "High-content fluorescence imaging of fixed cells", "instrument_or_platform": "Optical pooled screening (in situ sequencing + imaging)", "primary_metric": "Morphological feature vectors — cells are clustered by similarity of phenotypic profiles across imaging channels"}, "clustering": {"method": "Phenotypic similarity clustering of per-gene morphological profiles", "parameters": {"resolution": "Leiden algorithm on nearest-neighbor graph", "k_neighbors": "15"}}, "controls": {"negative_controls": "Non-targeting sgRNAs", "posit
...
[truncated]

In [27]:
# Preview the user prompt for one cluster (the bundle JSON wrapped in instructions).
USER_PROMPT_PREVIEW = make_single_cluster_analysis_user_prompt(
    PREVIEW_CLUSTER_ID, SCREEN_NAME, CLUSTER_ID_TO_BUNDLE_PATH_MAP
)
if TRUNCATE_PREVIEWS:
    print(
        USER_PROMPT_PREVIEW[:800] + ("\n...\n[truncated]" if len(USER_PROMPT_PREVIEW) > 800 else "")
    )
else:
    print(USER_PROMPT_PREVIEW)

Here is the evidence bundle JSON for cluster 121:

```json
{"screen_name": "mcpmodbranch_20260511_043334", "cluster_id": "121", "cluster_genes": [{"gene_symbol": "CCDC174", "up_features": "interphase_nucleus_area,interphase_cell_dapi_mass_displacement,interphase_cell_correlation_dapi_tubulin,interphase_nucleus_eccentricity,interphase_cell_area", "down_features": "interphase_nucleus_form_factor,interphase_nucleus_dapi_mean,interphase_nucleus_correlation_dapi_gh2ax", "phenotypic_strength": "2240/5299", "UniProt_functional_annotation": "Probably involved in neuronal development", "accession": "Q6PII3"}, {"gene_symbol": "DDA1", "up_features": "interphase_cell_area,interphase_cell_correlation_dapi_tubulin,interphase_nucleus_area", "down_features": "interphase_nucleus_correlation_dapi_gh2ax,inte
...
[truncated]

### 5.3 Query the LLM

Initialize the client. All three `QUERY_TYPE` branches below call `client.analyze(...)` and persist a per-cluster trace via `save_trace(...)`.

In [28]:
LLM_client = create_client(
    model=MODEL,
    api_key=os.getenv("ANTHROPIC_API_KEY"),
)
print(f"Client initialized: {type(LLM_client).__name__}")

Client initialized: AnthropicClient

#### Single cluster (smoke test)
Use this to validate one (mode, mcp) combo before fanning out. Make sure `QUERY_TYPE` is set to `"single"` in 5.1 to use this!

In [29]:
if QUERY_TYPE == "single":
    user_prompt = make_single_cluster_analysis_user_prompt(
        PREVIEW_CLUSTER_ID, SCREEN_NAME, CLUSTER_ID_TO_BUNDLE_PATH_MAP
    )
    parsed, raw_outputs = LLM_client.analyze(
        system_prompt=SYSTEM_PROMPT,
        user_prompt=user_prompt,
        mode=MODE,
        mcp=USE_MCP,
    )
    save_trace(
        RUN_DIR,
        PREVIEW_CLUSTER_ID,
        model=MODEL,
        mode=f"{MODE}_mcp" if USE_MCP else MODE,
        raw_response=raw_outputs.get("response_text", ""),
        tool_calls=raw_outputs.get("tool_calls", []),
        elapsed_s=raw_outputs.get("elapsed_s"),
        input_tokens=raw_outputs.get("input_tokens"),
        output_tokens=raw_outputs.get("output_tokens"),
        cost_usd=raw_outputs.get("cost_usd"),
        pricing_warning=raw_outputs.get("pricing_warning"),
        schema_warnings=raw_outputs.get("schema_warnings"),
        error=raw_outputs.get("error"),
        steps=raw_outputs.get("steps"),
    )
    if raw_outputs.get("error"):
        print(f"ERROR: {raw_outputs['error']}")
    else:
        meta = parsed.get("_validation_metadata", {})
        print(
            f"OK ({meta.get('time_seconds', '?')}s | "
            f"{meta.get('input_tokens', '?')}in / {meta.get('output_tokens', '?')}out | "
            f"${meta.get('cost_usd', 0):.4f})"
        )
        print(
            f"Predicted: {parsed.get('dominant_process', '?')} [{parsed.get('pathway_confidence', '?')}]"
        )
        out_path = RUN_DIR / f"phase1_single_cluster_LLM_analysis/{PREVIEW_CLUSTER_ID}_parsed.json"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(parsed, indent=2))
        print(f"Saved parsed JSON: {out_path}")

OK (144.6s | 110703in / 8007out | $0.4522)
Predicted: MYC transcriptional network and chromatin co-regulation [High]
Saved parsed JSON: output\mcpmodbranch_20260511_043334_analysis\phase1_single_cluster_LLM_analysis\121_parsed.json

#### Iterative (all clusters, sequential)
Required when `MODE='stepwise'` or `USE_MCP=True`. Per-cluster trace + summary cost printed.

In [30]:
if QUERY_TYPE == "iterative":
    results = {}
    cluster_metrics = {}
    mode_label = f"{MODE}_mcp" if USE_MCP else MODE

    for cluster_id in CLUSTER_ID_TO_BUNDLE_PATH_MAP.keys():
        print(f"  Cluster {cluster_id} [{mode_label}]...", end=" ", flush=True)
        user_prompt = make_single_cluster_analysis_user_prompt(
            cluster_id, SCREEN_NAME, CLUSTER_ID_TO_BUNDLE_PATH_MAP
        )
        try:
            parsed, raw_outputs = LLM_client.analyze(
                system_prompt=SYSTEM_PROMPT,
                user_prompt=user_prompt,
                mode=MODE,
                mcp=USE_MCP,
            )
        except Exception as e:
            print(f"ERROR: {e}")
            results[str(cluster_id)] = {"error": str(e)}
            cluster_metrics[str(cluster_id)] = {"error": str(e)}
            save_trace(
                RUN_DIR,
                str(cluster_id),
                model=MODEL,
                mode=mode_label,
                raw_response="",
                elapsed_s=0,
                error=str(e),
            )
            continue

        save_trace(
            RUN_DIR,
            str(cluster_id),
            model=MODEL,
            mode=mode_label,
            raw_response=raw_outputs.get("response_text", ""),
            tool_calls=raw_outputs.get("tool_calls", []),
            elapsed_s=raw_outputs.get("elapsed_s"),
            input_tokens=raw_outputs.get("input_tokens"),
            output_tokens=raw_outputs.get("output_tokens"),
            cost_usd=raw_outputs.get("cost_usd"),
            pricing_warning=raw_outputs.get("pricing_warning"),
            schema_warnings=raw_outputs.get("schema_warnings"),
            error=raw_outputs.get("error"),
            steps=raw_outputs.get("steps"),
        )

        err = raw_outputs.get("error")
        if err or parsed is None or "_validation_metadata" not in (parsed or {}):
            print(f"FAILED: {err or 'no parsed output'}")
            results[str(cluster_id)] = {"error": err or "no parsed output"}
            cluster_metrics[str(cluster_id)] = {
                "error": err or "no parsed output",
                "elapsed_s": raw_outputs.get("elapsed_s"),
                "cost_usd": raw_outputs.get("cost_usd"),
            }
            continue

        results[str(cluster_id)] = parsed
        meta = parsed.get("_validation_metadata", {})
        cluster_metrics[str(cluster_id)] = {
            "elapsed_s": meta.get("time_seconds"),
            "input_tokens": meta.get("input_tokens"),
            "output_tokens": meta.get("output_tokens"),
            "cost_usd": meta.get("cost_usd"),
            "tool_calls": meta.get("tool_calls", 0),
        }
        print(
            f"OK ({meta.get('time_seconds', '?')}s | "
            f"{meta.get('input_tokens', 0)}in / {meta.get('output_tokens', 0)}out | "
            f"${meta.get('cost_usd', 0):.4f}) — {parsed.get('dominant_process', '?')[:60]}"
        )

    # Run totals
    total_cost = sum((m.get("cost_usd") or 0) for m in cluster_metrics.values())
    total_time = sum((m.get("elapsed_s") or 0) for m in cluster_metrics.values())
    total_in = sum((m.get("input_tokens") or 0) for m in cluster_metrics.values())
    total_out = sum((m.get("output_tokens") or 0) for m in cluster_metrics.values())
    print(f"\nTotals: {total_time:.1f}s | {total_in}in / {total_out}out | ${total_cost:.4f}")

    # Save consolidated parsed results
    out_path = RUN_DIR / f"phase1_iterative_cluster_LLM_analysis/all_results.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(
            {
                "mode": mode_label,
                "model": MODEL,
                "cluster_metrics": cluster_metrics,
                "results": results,
            },
            indent=2,
        )
    )
    print(f"Saved: {out_path}")

#### Batch (Anthropic message batches API)
Submits all clusters to Anthropic's batch API; the call polls for completion and writes per-cluster outputs to disk. Results take up to 24h. **Disabled when `USE_MCP=True` or `MODE='stepwise'`** (validated in §5.1).

In [31]:
if QUERY_TYPE == "batch":
    _, batch_meta = LLM_client.analyze(
        system_prompt=SYSTEM_PROMPT,
        cluster_to_prompt_map=CLUSTER_ID_TO_BUNDLE_PATH_MAP,
        mode=MODE,
        mcp=False,  # enforced by §5.1
        batch=True,
        screen_name=SCREEN_NAME,
    )
    print(f"Batch ID: {batch_meta.get('batch_id')}")
    if batch_meta.get("errored_requests"):
        print(f"Errored: {batch_meta['errored_requests']}")

#### Batch retrieval (resume after closing the notebook)
If the batch is still pending and you closed the notebook, run this cell to poll using a saved batch ID. Batch results expire 24h after submission.

In [32]:
import anthropic
import time

screen_name = SCREEN_NAME  # or override
batch_id = None  # or override; will be auto-detected from intermediates dir

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

if not batch_id:
    intermediates_dir = Path(f"output/{screen_name}_analysis/intermediates")
    batch_files = sorted(intermediates_dir.glob("msg_batch_ID_*.txt"))
    if not batch_files:
        raise FileNotFoundError(f"No batch ID files found in {intermediates_dir}")
    batch_id = batch_files[-1].read_text().strip()
    print(f"Found batch ID: {batch_id} (from {batch_files[-1].name})")

while True:
    message_batch = client.messages.batches.retrieve(batch_id)
    if message_batch.processing_status == "ended":
        break
    print(f"Batch {batch_id} still processing...")
    time.sleep(60)

errored_requests = []
for result in client.messages.batches.results(batch_id):
    match result.result.type:
        case "succeeded":
            path = Path(
                f"output/{screen_name}_analysis/phase1_batch_cluster_LLM_analysis/{result.custom_id}_analysis_response.jsonl"
            )
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(str(result.result.message.content), encoding="utf-8")
            print(f"{result.custom_id}: saved → {path}")
        case "errored":
            error_obj = result.result.error
            error_type = getattr(getattr(error_obj, "error", None), "type", "unknown")
            error_msg = getattr(getattr(error_obj, "error", None), "message", None)
            print(f"{result.custom_id}: {error_type} -- {error_msg}")
            errored_requests.append(result.custom_id)
        case "expired":
            print(f"{result.custom_id}: expired")
            errored_requests.append(result.custom_id)

if errored_requests:
    print(f"\n{len(errored_requests)} request(s) failed: {errored_requests}")

FileNotFoundError: No batch ID files found in output\mcpmodbranch_20260511_043334_analysis\intermediates